### ISSUE TITLE
Volume Adjuster does not change volume and downgrade bitrate

### ISSUE THREAD

**Issue by igogo2** [inbasic/media-converter#13]
Hello,
My version is 0.1.8. Firefox 45.0.2 Windows.
1 After adjusting, the volume still the same and bitrate is downgraded to 24 kbps.
2 In some cases max level of 200% is too small. It would be grate to increase max level to 400%.

**Comment by inbasic** [comment]
This should be fixed on 0.1.9

**Comment by inbasic** [comment]
> 2 In some cases max level of 200% is too small. It would be grate to increase max level to 400%.

Just drop the converted file to the UI one more time.

**Comment by igogo2** [comment]
I've tried on 0.1.9.
Unfortunately 
1 After adjusting, the volume still the same and bitrate is downgraded to 24 kbps.
does not fixed.
